development:
  adapter: postgresql
  encoding: utf8
  database: translator_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: translator_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: translator_production
  pool: 5
  username: 
  password:
